# Trying some Threading 

This helps to gather tweets from the internet

In [22]:
import os
import time
import pandas as pd
import snscrape.modules.twitter as sntwitter
import datetime
from datetime import timedelta
import threading
import concurrent.futures
code_dir = os.path.dirname(os.getcwd())
print(code_dir)
parent_dir = os.path.dirname(code_dir)
print(parent_dir)
data_dir = os.path.join(parent_dir,"Data")
print(data_dir)
tweet_dir = os.path.join(parent_dir,"tweets_archive")
print(tweet_dir)

/Volumes/Elements/DataScience/dsa/capstone/Code
/Volumes/Elements/DataScience/dsa/capstone
/Volumes/Elements/DataScience/dsa/capstone/Data
/Volumes/Elements/DataScience/dsa/capstone/tweets_archive

In [7]:
def twittsearch(text_query,since_date, until_date, tweetcount):
    ta = time.perf_counter()
    
    
    tweets_list = []

    query = '{0} since:{1} until:{2} filter:has_engagement'.format(text_query, since_date, until_date)
    print(f'At {ta} querying for {since_date} to {until_date}')

    # Using TwitterSearchScraper to scrape data and append tweets to list

    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):

        if i>tweetcount:
            print (tweetcount)
            break
        
        tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.url,
                            tweet.lang,tweet.retweetedTweet,tweet.quotedTweet])

    # Creating a dataframe from the tweets list above

    tweets_df = pd.DataFrame(tweets_list, 
                             columns=['Datetime', 'TweetId', 'Text','TweetLink',
                                     "Language", "RTFrom", "QTFrom"])
    
    print("found {} tweets ranging from {} to {}".format(len(tweets_df),
                                                            tweets_df.Datetime.min(),tweets_df.Datetime.max()))
    
    print("dropping duplicates")   
    tweets_df = tweets_df.drop_duplicates(subset=['TweetId'])
    print("total of tweets now: {}".format(len(tweets_df)))
    print("english only")

    tweets_df = tweets_df[tweets_df["Language"]=='en']
    print("total of tweets now: {}".format(len(tweets_df)))
    tweets_df = tweets_df[tweets_df["RTFrom"].isna()]
    print("total of tweets now: {}".format(len(tweets_df)))
    tweets_df = tweets_df[tweets_df["QTFrom"].isna()]
    print("total of tweets now: {} ranging from {} to {}".format(len(tweets_df),
                                                                tweets_df.Datetime.min(),tweets_df.Datetime.max()))
    
    tweets_df = tweets_df[['Datetime', 'TweetId', 'Text','TweetLink']]
    tb = time.perf_counter()
    print(f'Completed querying for {since_date} to {until_date} at {tb}. Time elapsed {tb-ta}')      
    return tweets_df

In [16]:


since_date = '2021-08-01' # user must pick
until_date = '2021-08-18' # user must pick
mydates = pd.date_range(since_date,until_date).tolist()

mydates[0]

Timestamp('2021-08-01 00:00:00', freq='D')

In [17]:
twtsl = []

def datemaker (mydates):
#     print(f"running {mydates}")
    text_query = '("forest fire") OR wildfire OR bushfire OR \
(extreme heat) OR (record heat) OR heatwave OR ("heat wave") OR typhoon OR cyclone OR hurricane OR \
tornado OR ("storm surge") OR  blizzard OR snow OR ("ice storm") OR sleet OR thunderstorm OR \
hail OR flood OR flooding OR freeze OR frost OR (extreme cold) OR landslide OR tsunami OR ("tidal wave") OR \
earthquake OR eruption OR volcano OR lava OR lahar OR avalanche OR mudslide OR sinkhole'
    since_date = mydates.strftime("%Y-%m-%d")

    until_date= (mydates + timedelta(days = 1)).strftime("%Y-%m-%d")

    tweetcount=200000
    try: 
        tx = time.perf_counter()
        twtsl.append(twittsearch(text_query,since_date, until_date, tweetcount))
        ty = time.perf_counter() 
        
    except:
        print("------")
t1 = time.perf_counter()    
with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(datemaker, mydates)
t2 = time.perf_counter() 
print (f'Completed in {(t2-t1)/60)} minutes time')

At 15843.116165787 querying for 2021-08-01 to 2021-08-02At 15843.116624934 querying for 2021-08-02 to 2021-08-03
At 15843.118166143 querying for 2021-08-03 to 2021-08-04

At 15843.118976288 querying for 2021-08-04 to 2021-08-05
At 15843.127524289 querying for 2021-08-05 to 2021-08-06
At 15843.136223829 querying for 2021-08-06 to 2021-08-07
At 15843.138898175 querying for 2021-08-07 to 2021-08-08
At 15843.144811451 querying for 2021-08-08 to 2021-08-09
found 61895 tweets ranging from 2021-08-06 00:00:01+00:00 to 2021-08-06 23:59:59+00:00
dropping duplicates
total of tweets now: 61895
english only
total of tweets now: 33846
total of tweets now: 33846
total of tweets now: 31373 ranging from 2021-08-06 00:00:01+00:00 to 2021-08-06 23:59:59+00:00
Completed querying for 2021-08-06 to 2021-08-07 at 17917.244822817. Time elapsed 2115.94061503
found 61896 tweets ranging from 2021-08-06 00:00:01+00:00 to 2021-08-06 23:59:59+00:00
dropping duplicates
total of tweets now: 61896
english only
total of tweets now: 33847
total of tweets now: 33847
total of tweets now: 31374 ranging from 2021-08-06 00:00:01+00:00 to 2021-08-06 23:59:59+00:00
Completed querying for 2021-08-06 to 2021-08-07 at 17918.626472006. Time elapsed 2075.4902481769986
At 17918.666499461 querying for 2021-08-09 to 2021-08-10
found 56846 tweets ranging from 2021-08-01 00:00:00+00:00 to 2021-08-01 23:59:59+00:00
dropping duplicates
total of tweets now: 56846
english only
total of tweets now: 30272
total of tweets now: 30272
total of tweets now: 28292 ranging from 2021-08-01 00:00:00+00:00 to 2021-08-01 23:59:57+00:00
Completed querying for 2021-08-01 to 2021-08-02 at 18000.394429344. Time elapsed 2199.109352341
found 56846 tweets ranging from 2021-08-01 00:00:00+00:00 to 2021-08-01 23:59:59+00:00
dropping duplicates
total of tweets now: 56846
english only
total of tweets now: 30271
total of tweets now: 30271
total of tweets now: 28291 ranging from 2021-08-01 00:00:00+00:00 to 2021-08-01 23:59:57+00:00
Completed querying for 2021-08-01 to 2021-08-02 at 18028.322481081. Time elapsed 2185.206315293999
At 18028.359728153 querying for 2021-08-10 to 2021-08-11
found 56855 tweets ranging from 2021-08-07 00:00:00+00:00 to 2021-08-07 23:59:58+00:00
dropping duplicates
total of tweets now: 56855
english only
total of tweets now: 30147
total of tweets now: 30147
total of tweets now: 28025 ranging from 2021-08-07 00:00:00+00:00 to 2021-08-07 23:59:49+00:00
Completed querying for 2021-08-07 to 2021-08-08 at 18048.394009902. Time elapsed 2247.0864470039996
found 56855 tweets ranging from 2021-08-07 00:00:00+00:00 to 2021-08-07 23:59:58+00:00
dropping duplicates
total of tweets now: 56855
english only
total of tweets now: 30147
total of tweets now: 30147
total of tweets now: 28025 ranging from 2021-08-07 00:00:00+00:00 to 2021-08-07 23:59:49+00:00
Completed querying for 2021-08-07 to 2021-08-08 at 18125.743598908. Time elapsed 2282.604700733
At 18125.786618294 querying for 2021-08-11 to 2021-08-12
found 56209 tweets ranging from 2021-08-05 00:00:00+00:00 to 2021-08-05 23:59:59+00:00
dropping duplicates
total of tweets now: 56209
english only
total of tweets now: 29978
total of tweets now: 29978
total of tweets now: 27482 ranging from 2021-08-05 00:00:00+00:00 to 2021-08-05 23:59:49+00:00
Completed querying for 2021-08-05 to 2021-08-06 at 18129.547763894. Time elapsed 2328.2471000879996
found 56209 tweets ranging from 2021-08-05 00:00:00+00:00 to 2021-08-05 23:59:59+00:00
dropping duplicates
total of tweets now: 56209
english only
total of tweets now: 29978
total of tweets now: 29978
total of tweets now: 27482 ranging from 2021-08-05 00:00:00+00:00 to 2021-08-05 23:59:49+00:00
Completed querying for 2021-08-05 to 2021-08-06 at 18145.204635717. Time elapsed 2302.0771114279996
At 18145.24487458 querying for 2021-08-12 to 2021-08-13
found 61261 tweets ranging from 2021-08-04 00:00:00+00:00 to 2021-08-04 23:59:55+00:00
dropping duplicates
total of tweets now: 61261
english only
total of tweets now: 32620
total of tweets now: 32620
total of tweets now: 30112 ranging from 2021-08-04 00:00:00+00:00 to 2021-08-04 23:59:55+00:00
Completed querying for 2021-08-04 to 2021-08-05 at 18224.976119974. Time elapsed 2423.679105654999
found 59349 tweets ranging from 2021-08-02 00:00:00+00:00 to 2021-08-02 23:59:58+00:00
dropping duplicates
total of tweets now: 59349
english only
total of tweets now: 30418
total of tweets now: 30418
total of tweets now: 28227 ranging from 2021-08-02 00:00:00+00:00 to 2021-08-02 23:59:54+00:00
Completed querying for 2021-08-02 to 2021-08-03 at 18302.269057032. Time elapsed 2459.1524320980006
At 18302.308471466 querying for 2021-08-13 to 2021-08-14
found 59347 tweets ranging from 2021-08-02 00:00:00+00:00 to 2021-08-02 23:59:58+00:00
dropping duplicates
total of tweets now: 59347
english only
total of tweets now: 30416
total of tweets now: 30416
total of tweets now: 28226 ranging from 2021-08-02 00:00:00+00:00 to 2021-08-02 23:59:54+00:00
Completed querying for 2021-08-02 to 2021-08-03 at 18311.390726988. Time elapsed 2510.0972032520003
found 60561 tweets ranging from 2021-08-08 00:00:00+00:00 to 2021-08-08 23:59:58+00:00
dropping duplicates
total of tweets now: 60561
english only
total of tweets now: 29969
total of tweets now: 29969
total of tweets now: 27811 ranging from 2021-08-08 00:00:00+00:00 to 2021-08-08 23:59:58+00:00
Completed querying for 2021-08-08 to 2021-08-09 at 18361.992051919. Time elapsed 2518.847240467998
At 18362.034502162 querying for 2021-08-14 to 2021-08-15
found 61262 tweets ranging from 2021-08-04 00:00:00+00:00 to 2021-08-04 23:59:55+00:00
dropping duplicates
total of tweets now: 61262
english only
total of tweets now: 32621
total of tweets now: 32621
total of tweets now: 30112 ranging from 2021-08-04 00:00:00+00:00 to 2021-08-04 23:59:55+00:00
Completed querying for 2021-08-04 to 2021-08-05 at 18382.976420972. Time elapsed 2539.857444684001
At 18383.019684265 querying for 2021-08-15 to 2021-08-16
found 67914 tweets ranging from 2021-08-03 00:00:00+00:00 to 2021-08-03 23:59:57+00:00
dropping duplicates
total of tweets now: 67914
english only
total of tweets now: 37212
total of tweets now: 37212
total of tweets now: 34377 ranging from 2021-08-03 00:00:00+00:00 to 2021-08-03 23:59:57+00:00
Completed querying for 2021-08-03 to 2021-08-04 at 18677.037142559. Time elapsed 2875.741946922999
found 67914 tweets ranging from 2021-08-03 00:00:00+00:00 to 2021-08-03 23:59:57+00:00
dropping duplicates
total of tweets now: 67914
english only
total of tweets now: 37212
total of tweets now: 37212
total of tweets now: 34377 ranging from 2021-08-03 00:00:00+00:00 to 2021-08-03 23:59:57+00:00
Completed querying for 2021-08-03 to 2021-08-04 at 18678.848457515. Time elapsed 2835.7302913719996
At 18678.899711315 querying for 2021-08-16 to 2021-08-17
found 66028 tweets ranging from 2021-08-09 00:00:00+00:00 to 2021-08-09 23:59:58+00:00
dropping duplicates
total of tweets now: 66028
english only
total of tweets now: 36181
total of tweets now: 36181
total of tweets now: 33376 ranging from 2021-08-09 00:00:00+00:00 to 2021-08-09 23:59:58+00:00
Completed querying for 2021-08-09 to 2021-08-10 at 20142.205076779. Time elapsed 2223.5385773179987
At 20142.256369478 querying for 2021-08-17 to 2021-08-18
found 105127 tweets ranging from 2021-08-10 00:00:00+00:00 to 2021-08-10 23:59:59+00:00
dropping duplicates
total of tweets now: 105127
english only
total of tweets now: 57366
total of tweets now: 57366
total of tweets now: 52878 ranging from 2021-08-10 00:00:00+00:00 to 2021-08-10 23:59:59+00:00
Completed querying for 2021-08-10 to 2021-08-11 at 21567.307781047. Time elapsed 3538.9480528940003
At 21567.381604256 querying for 2021-08-18 to 2021-08-19
found 139242 tweets ranging from 2021-08-11 00:00:00+00:00 to 2021-08-11 23:59:57+00:00
dropping duplicates
total of tweets now: 139242
english only
total of tweets now: 72637
total of tweets now: 72637
total of tweets now: 67026 ranging from 2021-08-11 00:00:00+00:00 to 2021-08-11 23:59:57+00:00
Completed querying for 2021-08-11 to 2021-08-12 at 23084.161804399. Time elapsed 4958.375186104997
found 141565 tweets ranging from 2021-08-15 00:00:00+00:00 to 2021-08-15 23:59:58+00:00
dropping duplicates
total of tweets now: 141565
english only
total of tweets now: 63146
total of tweets now: 63146
total of tweets now: 58222 ranging from 2021-08-15 00:00:00+00:00 to 2021-08-15 23:59:57+00:00
Completed querying for 2021-08-15 to 2021-08-16 at 23347.289946114. Time elapsed 4964.270261849

found 142851 tweets ranging from 2021-08-14 00:00:00+00:00 to 2021-08-14 23:59:59+00:00
dropping duplicates
total of tweets now: 142851
english only
total of tweets now: 72835
total of tweets now: 72835
total of tweets now: 67142 ranging from 2021-08-14 00:00:00+00:00 to 2021-08-14 23:59:58+00:00
Completed querying for 2021-08-14 to 2021-08-15 at 23381.828759212. Time elapsed 5019.794257049998
found 147236 tweets ranging from 2021-08-12 00:00:00+00:00 to 2021-08-12 23:59:59+00:00
dropping duplicates
total of tweets now: 147236
english only
total of tweets now: 75080
total of tweets now: 75080
total of tweets now: 69543 ranging from 2021-08-12 00:00:00+00:00 to 2021-08-12 23:59:59+00:00
Completed querying for 2021-08-12 to 2021-08-13 at 23435.131060331. Time elapsed 5289.886185751002
found 134301 tweets ranging from 2021-08-16 00:00:00+00:00 to 2021-08-16 23:59:59+00:00
dropping duplicates
total of tweets now: 134301
english only
total of tweets now: 66974
total of tweets now: 66974
total of tweets now: 61561 ranging from 2021-08-16 00:00:00+00:00 to 2021-08-16 23:59:59+00:00
Completed querying for 2021-08-16 to 2021-08-17 at 23786.92080406. Time elapsed 5108.021092744999
found 142773 tweets ranging from 2021-08-13 00:00:00+00:00 to 2021-08-13 23:59:59+00:00
dropping duplicates
total of tweets now: 142773
english only
total of tweets now: 71284
total of tweets now: 71284
total of tweets now: 66021 ranging from 2021-08-13 00:00:00+00:00 to 2021-08-13 23:59:56+00:00
Completed querying for 2021-08-13 to 2021-08-14 at 23819.102466484. Time elapsed 5516.793995018001
found 142550 tweets ranging from 2021-08-17 00:00:00+00:00 to 2021-08-17 23:59:59+00:00
dropping duplicates
total of tweets now: 142550
english only
total of tweets now: 71508
total of tweets now: 71508
total of tweets now: 66019 ranging from 2021-08-17 00:00:00+00:00 to 2021-08-17 23:59:59+00:00
Completed querying for 2021-08-17 to 2021-08-18 at 25249.266414848. Time elapsed 5107.01004537
found 108332 tweets ranging from 2021-08-18 00:00:00+00:00 to 2021-08-18 19:38:26+00:00
dropping duplicates
total of tweets now: 108332
english only
total of tweets now: 51593
total of tweets now: 51593
total of tweets now: 47025 ranging from 2021-08-18 00:00:00+00:00 to 2021-08-18 19:38:26+00:00
Completed querying for 2021-08-18 to 2021-08-19 at 25595.391458853. Time elapsed 4028.0098545969995
Completed in 25331.468041829783 minutes time

In [ ]:
with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(datemaker, mydates)

In [12]:
tweets_df

NameError: name 'tweets_df' is not defined

In [21]:
alldp=pd.concat(twtsl)

In [23]:
alldp.to_csv(os.path.join(tweet_dir,"august.csv"),index = False)